/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from "./contracts";
export type { contracts };
export type { AgentRegistry } from "./AgentRegistry";
export * as factories from "./factories";
export { AgentRegistry__factory } from "./factories/AgentRegistry__factory";
export type { Hello } from "./contracts/Hello";
export { Hello__factory } from "./factories/contracts/Hello__factory";
